CREATE DATABASE www_employeedb;
USE www_employeedb;

DROP TABLE IF EXISTS `tbl_user`;
CREATE TABLE IF NOT EXISTS `tbl_user`(
	`UID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`USER_ID` VARCHAR(50) NOT NULL,
	`USER_PASSWORD` VARCHAR(32) NOT NULL,
	`USER_ROLE` INTEGER UNSIGNED NOT NULL,
	`FIRST_NAME` VARCHAR(50) NULL,
	`LAST_NAME` VARCHAR(50) NULL,
	`CONTACT_NUMBER` VARCHAR(20) NULL,
	`CONTACT_EMAIL` VARCHAR(50) NOT NULL,
	`STATUS` TINYINT NOT NULL DEFAULT '0',
	`PASSWORD_SEED` VARCHAR(10) NOT NULL,
	`RESETPASSWORD` VARCHAR(64) NULL,
	`ADD_DATETIME` DATETIME NOT NULL,
	`UPDATE_DATEIME` DATETIME NULL,
	`ADDED` VARCHAR(100) NULL,
	`UPDATED` VARCHAR(100) NULL,
	`LAST_LOGIN_TIME` DATETIME NULL,
	`IP_ADDRESS` VARCHAR(100) NULL,
	PRIMARY KEY(`UID`),
	INDEX IDX_USER (`USER_ID`),
	INDEX IDX_RESETPWD(`RESETPASSWORD`)	
)ENGINE=INNODB CHARACTER SET utf8;

DROP TABLE IF EXISTS `tbl_employee_info`;
CREATE TABLE IF NOT EXISTS `tbl_employee_info`(
	`EMPLOYEE_ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`FIRST_NAME` VARCHAR(100) NOT NULL,
	`LAST_NAME` VARCHAR(100) NOT NULL,
	`EMAIL` VARCHAR(100) NOT NULL,
	`PHONE_NUMBER` VARCHAR(100) NOT NULL,
	`INTERNAL_EXTENS` VARCHAR(20) NOT NULL,
	`FILE_NAME` VARCHAR(200) NOT NULL,
	`NAME_INDEX` VARCHAR(2) NOT NULL,
	`ADD_DATETIME` DATETIME NOT NULL,
	`UPDATE_DATETIME` DATETIME NULL,
	`ADDED` VARCHAR(50) NULL,
	`UPDATED` VARCHAR(50) NULL,
	PRIMARY KEY(`EMPLOYEE_ID`),
	INDEX IDX_NAME(`FIRST_NAME`, `LAST_NAME`),
	INDEX IDX_EMAIL(`EMAIL`),
	INDEX IDX_NAME_INDEX(`NAME_INDEX`)
) ENGINE=INNODB CHARACTER SET utf8;

DROP TABLE IF EXISTS `tbl_employee_photo`;
CREATE TABLE IF NOT EXISTS `tbl_employee_photo`(
	`PHOTO_ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`EMPLOYEE_ID` INTEGER UNSIGNED NOT NULL,
	`PHOTO_NAME` VARCHAR(255) NOT NULL,
	`PHOTO_TAG` TEXT NULL,
	`PHOTO_PATH` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`PHOTO_ID`),
	INDEX IDX_EMPLOYEE(`EMPLOYEE_ID`)
) ENGINE=INNODB CHARACTER SET UTF8;

DROP TABLE IF EXISTS `tbl_employee_meta`;
CREATE TABLE IF NOT EXISTS `tbl_employee_meta`(
	`META_ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`EMPLOYEE_ID` INTEGER UNSIGNED NOT NULL,
	`META_KEY` VARCHAR(255) NOT NULL,
	`META_VALUE` LONGTEXT NULL,
	PRIMARY KEY (`META_ID`),
	INDEX IDX_EMPLOYEE(`EMPLOYEE_ID`)
) ENGINE=INNODB CHARACTER SET utf8;
